obj-y += io.o idle.o irq.o timer.o dma.o
obj-y += devices.o
obj-y += proc_comm.o
obj-y += vreg.o
obj-y += clock.o clock-7x01a.o
obj-y += gpio.o generic_gpio.o

obj-$(CONFIG_MSM_SMD) += smd.o smd_tty.o

obj-$(CONFIG_MACH_HALIBUT) += board-halibut.o
obj-$(CONFIG_MACH_TROUT) += board-dream.o
