
# LED Core
obj-$(CONFIG_NEW_LEDS)			+= led-core.o
obj-$(CONFIG_LEDS_CLASS)		+= led-class.o
obj-$(CONFIG_LEDS_TRIGGERS)		+= led-triggers.o

# LED Platform Drivers
obj-$(CONFIG_LEDS_ATMEL_PWM)		+= leds-atmel-pwm.o
obj-$(CONFIG_LEDS_CORGI)		+= leds-corgi.o
obj-$(CONFIG_LEDS_LOCOMO)		+= leds-locomo.o
obj-$(CONFIG_LEDS_SPITZ)		+= leds-spitz.o
obj-$(CONFIG_LEDS_S3C24XX)		+= leds-s3c24xx.o
obj-$(CONFIG_LEDS_AMS_DELTA)		+= leds-ams-delta.o
obj-$(CONFIG_LEDS_NET48XX)		+= leds-net48xx.o
obj-$(CONFIG_LEDS_WRAP)			+= leds-wrap.o
obj-$(CONFIG_LEDS_H1940)		+= leds-h1940.o
obj-$(CONFIG_LEDS_COBALT_QUBE)		+= leds-cobalt-qube.o
obj-$(CONFIG_LEDS_COBALT_RAQ)		+= leds-cobalt-raq.o
obj-$(CONFIG_LEDS_PCA9532)		+= leds-pca9532.o
obj-$(CONFIG_LEDS_GPIO)			+= leds-gpio.o
obj-$(CONFIG_LEDS_CM_X270)              += leds-cm-x270.o
obj-$(CONFIG_LEDS_CPLD)			+= leds-cpld.o
obj-$(CONFIG_LEDS_CLEVO_MAIL)		+= leds-clevo-mail.o
obj-$(CONFIG_LEDS_HP6XX)		+= leds-hp6xx.o
obj-$(CONFIG_LEDS_FSG)			+= leds-fsg.o
obj-$(CONFIG_LEDS_LM2756)       += leds-lm2756.o
obj-$(CONFIG_LEDS_LM3535)       += leds-lm3535.o
obj-$(CONFIG_LEDS_ADP8862)      += leds-adp8862.o
obj-$(CONFIG_LEDS_PM7540_BTN)   += leds-pm7540-btn.o
obj-$(CONFIG_LEDS_PM7540_SOC)   += leds-pm7540-soc.o
obj-$(CONFIG_LEDS_PM7540_KPD)   += leds-pm7540-kpd.o
obj-$(CONFIG_LEDS_MORRISON_KPD) += leds-morrison-kpd.o
obj-$(CONFIG_LEDS_CAMERA)       += leds-camera.o
obj-$(CONFIG_LEDS_FAN5646)      += leds-fan5646.o 
obj-$(CONFIG_LEDS_PCA955X)		+= leds-pca955x.o
obj-$(CONFIG_LEDS_MSM_PMIC)		+= leds-msm-pmic.o

# LED Triggers
obj-$(CONFIG_LEDS_TRIGGER_TIMER)	+= ledtrig-timer.o
obj-$(CONFIG_LEDS_TRIGGER_IDE_DISK)	+= ledtrig-ide-disk.o
obj-$(CONFIG_LEDS_TRIGGER_HEARTBEAT)	+= ledtrig-heartbeat.o
obj-$(CONFIG_LEDS_TRIGGER_DEFAULT_ON)	+= ledtrig-default-on.o
obj-$(CONFIG_LEDS_TRIGGER_SLEEP)	+= ledtrig-sleep.o
