#
# Makefile for the kernel multimedia device drivers.
#

obj-y        := dvb-core/ frontends/ ttpci/ ttusb-dec/ ttusb-budget/ b2c2/ bt8xx/ dvb-usb/ pluto2/ dm1105/

obj-$(CONFIG_DVB_FIREDTV)	+= firewire/
obj-$(CONFIG_MOT_FEAT_MDTV)     += siano/
