obj-y += dal.o
obj-y += q6audio.o
obj-y += pcm_out.o
obj-y += pcm_in.o
obj-y += mp3.o
obj-y += routing.o
obj-y += audio_ctl.o
ifeq ($(CONFIG_720P_CAMERA),y)
obj-y += msm_q6vdec-v2.o
obj-y += msm_q6venc-v2.o
else
obj-y += msm_q6vdec.o
obj-y += msm_q6venc.o
endif
obj-y += dsp_debug.o
