#
# Makefile for the Motorola drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_KERNEL_MOTOROLA)      += esd_poll.o
obj-$(CONFIG_KERNEL_MOTOROLA)      += mot_dev.o
obj-$(CONFIG_KERNEL_MOTOROLA)      += mot_handover.o
obj-$(CONFIG_MACH_CALGARY)      += esd_poll.o
obj-$(CONFIG_MACH_MOT)		+= esd_poll.o
obj-$(CONFIG_MACH_CALGARY)      += mot_dev.o
obj-$(CONFIG_MACH_CALGARY)      += mot_handover.o
